// Stylesheets every surface that renders authored content must load, in order:
// token definitions first (Open Props + the -hsl triplets the theme uses), then
// our themed normalize floor, whose `:where()` rules sit at specificity 0-0-0.
//
// Shared so the GrapesJS canvas (`CANVAS_STYLE_URLS`, which appends the RTE's
// stylesheet) and the theme admin's style-book iframe cannot drift apart — a
// difference between them would make the style book lie about what a block
// looks like on a page.
//
// The `/vendor/` files are generated by scripts/sync-vendor-css.mjs
// (predev / prebuild / postinstall); `tc-normalize.css` is tracked in public/.

export const CONTENT_STYLE_URLS = [
  "/vendor/open-props.min.css",
  "/vendor/open-props-colors-hsl.min.css",
  "/tc-normalize.css",
] as const
